<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class TopupPackagesSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('topup_packages')->insert([
            [
                'game_id' => 1,
                'name' => 'ML Diamond Pack 86',
                'description' => 'Get 86 Diamonds for Mobile Legends',
                'image' => 'https://cdn1.codashop.com/images/106_5e7a01a7-89b9-4b13-a512-a3e72f63f0d1_product/1760335203562_e4990cee-4020-4a74-8fc2-ae7f68fdabcd.png',
                'amount' => 86,
                'price' => 100,
                'fullprice' => 2.99,
                'best_seller' => 0,
                'discount' => '-23%',
                'Unit' => 'Diamonds',
                'currency' => 'USD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'game_id' => 1,
                'name' => 'ML Diamond Pack 172',
                'description' => 'Get 172 Diamonds for Mobile Legends',
                'image' => 'https://cdn1.codashop.com/images/106_5e7a01a7-89b9-4b13-a512-a3e72f63f0d1_product/1760335203009_d549995d-4641-48ed-80d0-c8f6259840f2.png',
                'amount' => 172,
                'price' => 100,
                'Unit' => 'Diamonds',
                'fullprice' => 4.99,
                'best_seller' => 0,
                'discount' => '-23%',
                'currency' => 'USD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'game_id' => 1,
                'name' => 'ML Diamond Pack 172',
                'description' => 'Get 172 Diamonds for Mobile Legends',
                'image' => 'https://cdn1.codashop.com/images/106_5e7a01a7-89b9-4b13-a512-a3e72f63f0d1_product/1760335203286_6878d3f6-b882-4a98-8e79-8d631d7fb683.png',
                'amount' => 172,
                'price' => 200,
                'best_seller' => 1,
                'fullprice' => 4.99,
                'discount' => '-23%',
                'Unit' => 'Diamonds',
                'currency' => 'USD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'game_id' => 1,
                'name' => 'ML Diamond Pack 172',
                'description' => 'Get 172 Diamonds for Mobile Legends',
                'image' => 'https://cdn1.codashop.com/images/106_5e7a01a7-89b9-4b13-a512-a3e72f63f0d1_product/1760335203009_d549995d-4641-48ed-80d0-c8f6259840f2.png',
                'amount' => 256,
                'price' => 200,
                'fullprice' => 6.99,
                'discount' => '-23%',
                'best_seller' => 1,
                'Unit' => 'Diamonds',
                'currency' => 'USD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'game_id' => 2,
                'name' => 'Honor of Kings 100 Gems',
                'description' => 'Top up 100 Gems for Honor of Kings',
                'image' => 'https://example.com/hok100.png',
                'amount' => 100,
                'price' => 2.5,
                'best_seller' => 0,
                'fullprice' => 3.5,
                'discount' => '-23%',
                'Unit' => 'Gems',
                'currency' => 'USD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'game_id' => 3,
                'name' => 'PUBG Mobile 300 UC',
                'description' => 'Top up 300 UC for PUBG Mobile',
                'image' => 'https://cdn1.codashop.com/S/content/common/images/denom-image/PUBG/325_PUBG_UC.png',
                'amount' => 300,
                'best_seller' => 0,
                'price' => 5.99,
                'fullprice' => 7.99,
                'discount' => '-23%',
                'Unit' => 'UC',
                'currency' => 'USD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'game_id' => 4,
                'name' => 'Garena Shells 980',
                'description' => 'Get 980 Garena Shells',
                'image' => 'https://cdn1.codashop.com/S/content/common/images/denom-image/GARENA_SHELLS/GARENA_Shells.png',
                'amount' => 980,
                'price' => 14.99,
                'fullprice' => 19.99,
                'best_seller' => 0,
                'discount' => '-23%',
                'Unit' => 'Shells',
                'currency' => 'USD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'game_id' => 5,
                'name' => 'Zepeto Coins 500',
                'description' => 'Top up 500 Zepeto Coins',
                'image' => 'https://cdn1.codashop.com/images/600_e1a0e531-2c0f-4902-8ca0-a1a14ac060ed_product/1758468806233_3e8b9a64-4809-4763-94a9-857375eb1d91.png',
                'amount' => 500,
                'best_seller' => 0,
                'price' => 9.99,
                'Unit' => 'Coins',
                'fullprice' => 12.99,
                'discount' => '-23%',
                'currency' => 'USD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'game_id' => 6,
                'name' => 'EA FC',
                'description' => 'EA FC',
                'image' => 'https://cdn1.codashop.com/images/826_219b1202-df20-4fe8-bfcb-d2689d381d31_823ff62524a33a1ea5aee54da1ea2dbe_image/a170279f4510f8f5734a423af9d02118.png',
                'amount' => 500,
                'best_seller' => 0,
                'price' => 9.99,
                'Unit' => 'Coins',
                'fullprice' => 12.99,
                'discount' => '-23%',
                'currency' => 'USD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
